### ISSUE TITLE
Pokemon Red Full Color Hack Does Not Run

### ISSUE THREAD

**Issue by Knifethrower** [shilga/rp2040-gameboy-cartridge-firmware#1]
The Pokemon Red full color hack does not start. When you attempt to load the rom the screen stays white after the gameboy logo goes way and the game hangs without launching at this point.
https://www.romhacking.net/hacks/1385/

**Comment by shilga** [comment]
I looked into it and the main culprit is that the color hack lets the game still run on MBC3. I only implemented the double speed support for MBC5 as this it the only MBC which supports this mode. I'm not sure if this ROM would run on a real cartridge.

I'll have a look of what I can do. It should be possible to get it running.

**Comment by shilga** [comment]
I made it possible to run this. Update your cartridge firmware to [0.3.0](https://github.com/shilga/rp2040-gameboy-cartridge-firmware/releases/tag/0.3.0) and then upload the ROM again using the WebUSB application. I needed to change something there too, to make it work.

Have fun.
