### ISSUE TITLE
Is 128Mbit flash a necessity?

### ISSUE THREAD

**Issue by gezzerlol** [shilga/rp2040-gameboy-cartridge-firmware#4]
Could this firmware work with 64, 32 and 16 mbit versions of the same series flash?

**Comment by shilga** [comment]
In general it would work but not without modifications. The savegames and the index is stored in a littlefs partition in the last 2MiB.

In general I would suggest to not go smaller then 64 mbit. A lot of popular ROMs are 4 MiB and you need some space for firmware and savegame.

**Comment by gezzerlol** [comment]
I ordered 5 pcbs, will order one 128mbit from digikey, and a local supplier has the other capacities at great discounts. Let's see if I can do the modifications. Thanks for the tip!

**Comment by shilga** [comment]
Have a look at the following places:
- linkerscript https://github.com/shilga/rp2040-gameboy-cartridge-firmware/blob/3923152458b0ab4cd39ab4c831300a85c56092f1/linkerscript.ld#L28
- MAX_BANKS define https://github.com/shilga/rp2040-gameboy-cartridge-firmware/blob/3923152458b0ab4cd39ab4c831300a85c56092f1/GlobalDefines.h#L44C1-L44C22
- PICO_FLASH_SIZE_BYTES define https://github.com/shilga/rp2040-gameboy-cartridge-firmware/blob/3923152458b0ab4cd39ab4c831300a85c56092f1/MyBoard.h#L74

Not guaranteed that this is everything that needs to be changed, but sounds about rightish. The FLASH_SIZE also defines the position of the filesystem. I subtracts 2MiB from this size as the start. The maxbanks which is displayed in the WebUSB GUI is actually dynamically loaded from the cartridge. So no need to change anything there.
