### ISSUE TITLE
gb-photo / photo-remote.gb not working

### ISSUE THREAD

**Issue by explit7** [shilga/rp2040-gameboy-cartridge-firmware#8]
GB-Photo Remote Controller not working on Croco Catridge
https://github.com/untoxa/gb-photo
Tried this gb. File
https://github.com/untoxa/gb-photo/releases/download/v1.8/photo.zip

![photo-remote](https://github.com/user-attachments/assets/a0cbb1ea-b75f-48cd-8cc2-5d961c16becc)

**Comment by shilga** [comment]
It's probably because the name is empty. There is no name supplied in the ROM (error of the ROM). But the interface allows you to edit the name before uploading. Just click at the area where the name should be and start typing.

**Comment by explit7** [comment]
That worked, thanks!
